<?php
$collection = $this->getStatement();
$flag = $this->isAdminPage() && $this->hasPermission('Admin\\Sales\\Order::view');
?>
<div class="statement">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="text-center"><?php echo $this->translate('Balance') ?></th>
                <th class="text-center"><?php echo $this->translate('Comment') ?></th>
                <th class="text-center"><?php echo $this->translate('Order ID') ?></th>
                <th class="text-center"><?php echo $this->translate('Status') ?></th>
                <th class="text-center"><?php echo $this->translate('Date') ?></th>
            </tr>
        </thead>
        <?php if (count($collection)): ?>
            <tbody>
                <?php foreach ($collection as $balance): ?>
                    <tr class="text-center">
                        <td><?php echo (float) $balance['amount'] ?></td>
                        <td><?php echo $this->translate($balance['comment']) ?></td>
                        <td>
                            <?php if ($flag && $balance['order_id']): ?>
                                <a href="<?php echo $this->getAdminUrl('sales_order/view/?id='), $balance['order_id'] ?>"><?php echo $balance['increment_id'] ?></a>
                            <?php else: ?>
                                <?php echo $balance['increment_id'] ?>
                            <?php endif; ?>
                        </td>
                        <td><?php echo $this->translate($balance['status'] ? 'Payment Success' : 'Pending Payment') ?></td>
                        <td><?php echo $balance['created_at'] ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center">
                        <?php echo $this->getChild('pager')->setCollection($collection); ?>
                    </td>
                </tr>
            </tfoot>
        <?php else: ?>
            <tfoot>
                <tr>
                    <td colspan="5" class="text-center"><?php echo $this->translate('No data to display') ?></td>
                </tr>
            </tfoot>
        <?php endif; ?>
    </table>
</div>