<?php
$account = new Redseanet\Forum\ViewModel\Account;
$count = $account->getCount();
?>
<ul class="header-right col-sm-12 col-md-12">
    <li class="col-sm-2 col-md-2"><a href="<?php echo $this->getBaseUrl('forum/category/') ?>"><?php echo $this->translate('Find') ?></a></li>
    <li class="col-sm-2 col-md-2"><a href="<?php echo $this->getBaseUrl('allcategory.html') ?>"><?php echo $this->translate('Buy') ?></a></li>
    <li class="col-sm-2 col-md-2"><a href="<?php echo $this->getBaseUrl('forum/social/dynamic/') ?>"><?php echo $this->translate('Following') ?></a></li>
    <li class="col-sm-2 col-md-2">
        <a href="<?php echo $this->getBaseUrl('forum/account/') ?>"><?php echo $this->translate('Me') ?></a>
        <?php if ($count): ?>
            <a class="notice prompt-txt" href="<?php echo $this->getBaseUrl('forum/account/') ?>"><?php echo $count; ?></a>
        <?php endif; ?>
    </li>
</ul>