<?php
$bargains = $this->getBargains();
$currency = $this->getContainer()->get('currency');
$languageId = $this->getLanguageId();
?>
<?php if (count($bargains)): ?>
    <ul class="products-list row pe-1 ms-0 ps-0">
        <?php
        foreach ($bargains as $bargain) {
            $thumbnail = $bargain->getThumbnail()->load(true);
            $thumbnailImage = $this->getPubUrl("frontend/images/placeholder.png");
            if (isset($thumbnail[0]["real_name"])) {
                $thumbnailImage = $this->getResourceUrl('image/resized/300x/' . $thumbnail[0]["real_name"]);
            }
            $bargainId = $bargain->getId();
            ?>
            <li class="item col-lg-3 col-md-4 col-6 ps-1">
                <div class="itemc">
                    <a href="<?php echo $this->getBaseUrl("bargain/index/?bargain=" . $bargainId); ?>" title="<?php echo $bargain['name'][$languageId] ?>" class="product-image">
                        <img loading="lazy" src="<?php echo $thumbnailImage ?>" alt="<?php echo $bargain['name'][$languageId] ?>" />
                    </a>
                    <h6 class="product-name text-center">
                        <a href="<?php echo $this->getBaseUrl("bargain/index/?bargain=" . $bargainId); ?>" title="<?php echo $bargain['name'][$languageId] ?>">
                            <?php echo $bargain['name'][$languageId] ?>
                        </a>
                    </h6>
                    <div class="price-box">
                        <span class="regular-price font-20">
                            <span class="badge  text-bg-danger"><?php echo $this->translate('Price') ?></span>
                            <span class="price" data-price="<?php echo $currency->convert($bargain['min_price'], true) ?>"><?php echo $currency->convert($bargain['min_price'], true) ?></span>
                        </span>
                        <span class="old-price">
                            <span class="badge badge-secondary"><?php echo $this->translate('MSRP') ?></span>
                            <span class="price" data-price="<?php echo $bargain['price'] ?>"><?php echo $currency->convert($bargain['price'], true) ?></span>
                        </span>
                    </div>
                </div>
            </li>
            <?php
        }
        ?>
    </ul>
<?php else: ?>
    <p class="no-product"><?php echo $this->translate('There are no bargains matching the selection.') ?></p>
                            <?php endif ?>