<?php
$order = $this->getVariable('order');
$currency = $order->getCurrency();
?>
<div class="clearfix">
    <div class="card panel-default">
        <div class="card-header">
            <h4 class="card-title"><?php echo $this->translate('Order Infomation', [], 'sales') ?></h4>
        </div>
        <div class="card-body">
            <?php echo $this->translate('ID'), ': ', $order['increment_id'] ?><br />
            <?php echo $this->translate('Status'), ': ' . '<span class="sys-red">' . $this->translate($order->getStatus()->offsetGet('name'), [], 'sales') ?></span><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?><br />
            <?php echo $this->translate('Placed at'), ': ', $order['created_at'] ?>
            <?php if ($order['customer_note']): ?><br />
                <?php echo $this->translate('Message'), ': ', $order['customer_note'] ?>
            <?php endif ?>
        </div>
    </div>
    <div class="card panel-default">
        <div class="card-header clearfix">
            <h4 class="card-title float-start"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
        </div>
        <div class="card-body">
            <?php echo ($order->offsetGet('shipping_address') ? nl2br($order->offsetGet('shipping_address')) : "") ?>
        </div>
    </div>
    <?php if ($method = $order->getShippingMethod()): ?>
        <div class="card panel-default">
            <div class="card-header">
                <h4 class="card-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
            </div>
            <div class="card-body">
                <?php echo $this->translate($method->getLabel()) ?>
            </div>
        </div>
    <?php endif ?>
    <div class="card panel-default">
        <div class="card-header">
            <h4 class="card-title"><?php echo $this->translate('Payment Method', [], 'sales') ?></h4>
        </div>
        <div class="card-body">
            <?php echo $this->translate($order->getPaymentMethod()->getLabel()), '<br />', $this->translate('The order was placed using %s', [$order->offsetGet('currency')], 'sales') ?>
        </div>
    </div>
    <div class="card panel-default wide">
        <div class="card-header">
            <h4 class="card-title"><?php echo $this->translate('Product(s)') ?></h4>
        </div>
        <div class="card-body grid">

            <div class="d-flex fw-bold pt-2 pb-2 mb-2 border-bottom">
                <div class="col-md-6 col-10"> 
                    <?php echo $this->translate('Product') ?>
                </div>
                <div class="col-md-2 d-none d-md-block"> 
                    <?php echo $this->translate('SKU', [], 'sales') ?>
                </div>
                <div class="col-1 d-none d-md-block"> 
                    <?php echo $this->translate('Price', [], 'sales') ?>
                </div>
                <div class="col-1 d-none d-md-block"> 
                    <?php echo $this->translate('Qty', [], 'sales') ?>
                </div>
                <div class="col-md-2 col-2"> 
                    <?php echo $this->translate('Total', [], 'sales') ?>
                </div>
            </div>
            <?php
            foreach ($order->getItems() as $item):
                $product = $item['product'];
                $options = json_decode($item['options'], true);
                $thumbnail = $product->getThumbnail($options);
                ?>
                <div class="d-flex pt-md-5 pb-md-5 p-3 p-3"<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                    <div class="col-md-6 col-10 d-flex"> 
                        <div>
                            <a href="<?php echo $product->getUrl() ?>">
                                <img class="shadow rounded-2" src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/' . $thumbnail) : $thumbnail ?>" width="60" alt="<?php echo $item['product_name'] ?>" />
                            </a>
                        </div>
                        <div class="text-break ps-2">
                            <a href="<?php echo $product->getUrl() ?>" class="text-break">
                                <?php echo $item['product_name'] ?>
                            </a>
                            <?php
                            if ($item['product_id'] && count($options)):
                                ?>
                                <dl class="options font-12">
                                    <?php
                                    foreach ($product->getOptions() as $option):
                                        if (isset($options[$option->getId()])):
                                            ?>
                                            <dt><?php echo $option['title'] ?></dt>
                                            <dd><?php echo in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ? $option->getValue($options[$option->getId()]) : $options[$option->getId()] ?></dd>
                                            <?php
                                        endif;
                                    endforeach;
                                    ?>
                                </dl>
                            <?php endif ?>
                            <p class="mb-0 pb-0 d-block d-md-none sys-gray font-12"><?php echo $this->translate('SKU', [], 'sales').': '.$item['sku'] ?></p>
                            <p class="mb-0 pb-0 d-block d-md-none sys-gray font-12"><?php echo $currency->format($item['price']) ?></p>
                            <p class="mb-0 pb-0 d-block d-md-none sys-gray font-12"><?php echo 'X '.$item['qty'] ?></p>
                        </div>
                    </div>
                    <div class="col-2 d-none d-md-block"> 
                        <?php echo $item['sku'] ?>
                    </div>
                    <div class="col-1 d-none d-md-block"> 
                        <?php echo $currency->format($item['price']) ?>
                    </div>
                    <div class="col-1 d-none d-md-block"> 
                        <?php echo (float) $item['qty'] ?>
                    </div>
                    <div class="col-md-2 col-2"> 
                        <?php echo $currency->format($item['total']) ?>
                    </div>
                </div>
            <?php endforeach ?>
            <div class="border-top pt-md-4 pt-2">
                <dl class="float-end">
                    <dt><?php echo $this->translate('Subtotal', [], 'sales') ?>: <?php echo $currency->format($order->offsetGet('subtotal')) ?></dt>
                    <dt><?php echo $this->translate('Shipping &amp; Handling', [], 'sales') ?>: <?php echo $currency->format($order->offsetGet('shipping')) ?></dt>

                    <?php if ((float) $order->offsetGet('tax')): ?>
                        <dt><?php echo $this->translate('Tax', [], 'sales') ?>: <?php echo $currency->format($order->offsetGet('tax')) ?></dt>
                    <?php endif ?>
                    <?php
                    if ((float) $order->offsetGet('discount')):
                        $discount = json_decode($order->offsetGet('discount_detail'), true);
                        foreach ($discount as $type => $price):
                            ?>
                            <dt><?php
                                $text = $this->translate('Discount(' . $type . ')', [], 'sales');
                                echo $text[0] === 'D' ? $this->translate('Discount(%s)', [$type], 'sales') : $text
                                ?>: <?php echo (is_array($price) ? $currency->convert($price["total"], true) : $currency->convert($price, true)) ?></dt>
                            <?php
                        endforeach;
                    endif;
                    ?>
                    <dt><?php echo $this->translate('Grand Total', [], 'sales') ?>: <?php echo $currency->format($order->offsetGet('total')) ?></dt>
                    <?php if ((float) $order->offsetGet('total_refunded')): ?>
                        <dt><?php echo $this->translate('Total Refunded', [], 'sales') ?>: <?php echo $currency->format($order->offsetGet('total_refunded')) ?></dt>

                    <?php endif ?>
                </dl>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
