<?php
$config = $this->getConfig();
$new = strtotime('-' . $config['forum/post/new_days'] . 'days');
$current = $this->getSegment('customer')->get('hasLoggedIn') ? $this->getSegment('customer')->get('customer')['id'] : 0;
?>
<div role="tabpanel">
    <div class="d-none d-md-block">
     <ul class="main-title nav nav-tabs" id="myTab" role="tablist">
        <li class="active">
            <a href="#panel-1" class="main-publish h5" aria-controls="panel-1" role="tab" data-bs-toggle="tab"><?php echo $this->translate("My Release"); ?></a>
        </li>
    </ul>   
    </div>
    
    <ul class="nav nav-tabs d-md-none mt-4" id="myTab" role="tablist">
        <li class="active">
            <a href="#panel-1" class="main-publish h5" aria-controls="panel-1" role="tab" data-bs-toggle="tab"><?php echo $this->translate("My Release"); ?></a>
        </li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="panel-1">
            <div class="grid masonry-container">
                <ul class="products-grid masonry clearfix" id="masonry"  data-url="<?php echo $this->getBaseUrl();?>forum/account/?is_json=true">
                    <li class="item publish-plus col-6 col-sm-4 col-md-4">
                        <a href="<?php echo $this->getBaseUrl('forum/post/publish/'); ?>">
                            <i class="fa fa-plus" aria-hidden="true"></i>
                            <span><?php echo $this->translate("Add New Article"); ?></span>
                        </a>
                    </li>
                    <?php
                    $posts = $this->getPosts();
                    if (count($posts)):
                        foreach ($posts as $post):
                            $thumbnail = $post->getThumbnail();
                            $count = $post->getLikeCount();
                            $customer=$post->getCustomer();
                            if ($current == $post['customer_id']):
                                ?><li class="item col-6 col-sm-4 col-md-4<?php if ($post['poll_id']): ?> poll<?php
                                endif;
                                if (strtotime($post['created_at']) >= $new):
                                    ?> new<?php
                                    endif;
                                    if (strtotime($post['is_hot']) >= $new):
                                        ?> hot<?php endif ?>">
                                    <div class="item-list">
                                        <div class="dropdown text-end">
                                            <a id="dLabel" data-target="#" href="#" class="ellipsis-btn" data-bs-toggle="dropdown" aria-expanded="false" role="button" aria-haspopup="true">
                                                <span class="fa fa-ellipsis-h" aria-hidden="true"></span>
                                            </a>
                                            <ul class="dropdown-menu">
                                                <li><a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/postEdit/?id='), $post['id'] ?>"><?php echo $this->translate('Edit') ?></a></li>
                                                <li><a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/remove/?id='), $post['id'] ?>" class="remove" data-method="delete" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>"><?php echo $this->translate('Delete') ?></a></li>
                                            </ul>
                                        </div>
                                        <a href="<?php echo $post->getUrl() ?>" class="product-image">
                                            <img src="<?php echo $thumbnail ? $this->getUploadedUrl('forum/'.$thumbnail) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg'); ?>" />
                                        </a>
                                        <div class="product-text">
                                            <h6 class="product-name"><a href="<?php echo $post->getUrl() ?>"><?php echo $post['title'] ?></a></h6>
                                            <div class="product-user">
                                                <a href="<?php echo $this->getBaseUrl("forum/space/?customer_id=" . $customer['id']) ?>"><img class="rounded-circle" src="<?php echo $customer['avatar'] ? $this->getUploadedUrl('customer/avatar/' . $customer['avatar']) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" alt="<?php echo $customer['username'] ?>" /></a>
                                                <span class="product-userName">
                                                    <a href="<?php echo $this->getBaseUrl("forum/space/?customer_id=" . $customer['id']) ?>"><?php echo $customer['username'] ?></a>
                                                    <span class="publish-time"><?php echo $this->getTime($post['created_at']); ?></span>
                                                </span>
                                                <?php if ($current): ?>
                                                    <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like product-heart" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>" class="product-heart">
                                                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                                                        <span><?php echo $count; ?></span>
                                                    </a>
                                                    <?php
                                                else:
                                                    ?>
                                                    <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>" class="product-heart">
                                                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                                                        <span><?php echo $count; ?></span>
                                                    </a>
                                                <?php
                                                endif;
                                                ?>
                                            </div>
                                        </div>
                                        <div><?php 
                            if(!empty($post['tags'])){
                                foreach (explode(",", $post['tags']) as $tag){
                                    echo "<span style='background-color:#f5f4f4;display:inline-block;margin:5px; padding:5px;border-radius:5px;'>".$tag."</span>";
                                }
                            }
                            ?></div>
                                    </div>
                                </li>
                                <?php
                            endif;
                        endforeach;
                        ?>
                        <?php
                    else:
                        ?>
                        <p class="empty text-center"><?php echo $this->translate('No post available right now.') ?></p>
                    <?php
                    endif;
                    ?>
                </ul>
            </div>
        </div>
        
    </div>
</div>
<div class="main-end col-12">
    <span class="end-text">END</span>
</div>
