<?php
$application = $this->getVariable('model');
$language = @$model->getCustomer()->getLanguage()['code'];
$order = $application->getOrder();
$status = $application['status'];
$currency = $order->getCurrency();
?>
<table class="table table-no-border">
    <thead>
        <tr class="text-nowrap">
            <th style="text-align:left" colspan="2"><?php echo $this->translate('Product Infomation', [], 'catalog', $language) ?></th>
            <th style="text-align:center"><?php echo $this->translate('Price', [], 'catalog', $language) ?></th>
            <th style="text-align:center"><?php echo $this->translate('Refund Qty', [], 'sales', $language) ?></th>
            <th style="text-align:center"><?php echo $this->translate('Total', [], 'catalog', $language) ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $items = $application->getItems();
        $flag = true;
        foreach ($items as $item):
            $product = $item['product'];
            $options = json_decode($item['options'], true);
            $thumbnail = $product->getThumbnail($options);
            ?>
            <tr class="refund-list">
                <td>
                    <img src="<?php echo strpos($thumbnail, '//') === false ? $this->getResourceUrl('image/' . $thumbnail) : $thumbnail ?>" alt="<?php echo $product['name'] ?>" width="100" height="100" />
                </td>
                <td>
                    <h4 class="product-name"><?php echo $product['name'] ?></h4>
                    <?php
                    if ($item['product_id'] && count($options)):
                        ?>
                        <dl class="options">
                            <?php
                            foreach ($product->getOptions() as $option):
                                if (isset($options[$option->getId()])):
                                    ?>
                                    <dt><?php echo $option['title'] ?></dt>
                                    <dd>
                                        <?php
                                        echo (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                $option->getValue($options[$option->getId()]) : $options[$option->getId()])
                                        ?>
                                    </dd>
                                    <?php
                                endif;
                            endforeach;
                            ?>
                        </dl>
                    <?php endif ?>
                </td>
                <td class="text-center"><?php echo $currency->convert($item['base_price'], true) ?></td>
                <td class="text-center"><?php echo (float) $item['refunded_qty'] ?></td>
                <td class="text-center"><?php echo $currency->convert($item['base_price'] * $item['refunded_qty'], true) ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
