<div id="modal-account" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form action="<?php echo $this->getBaseUrl('balance/statement/saveAccount/') ?>" method="post" data-ajax="true">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <input type="hidden" name="id" />
                <div class="modal-header">
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo $this->translate('Edit Account') ?></h4>
                </div>
                <div class="modal-body fieldset">
                    <div class="input-box">
                        <label for="type" class="col-form-label"><?php echo $this->translate('Account Type') ?></label>
                        <div class="cell">
                            <select id="type" name="type" class="form-control required">
                                <?php foreach ($this->getType() as $id => $name): ?>
                                    <option value="<?php echo $id ?>"><?php echo $this->translate($name) ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="input-box">
                        <label for="type" class="col-form-label"><?php echo $this->translate('Account Name') ?></label>
                        <div class="cell">
                            <input type="text" id="name" name="detail[name]" class="form-control required" />
                        </div>
                    </div>
                    <div class="input-box">
                        <label for="id" class="col-form-label"><?php echo $this->translate('Account ID') ?></label>
                        <div class="cell">
                            <input type="text" id="id" name="detail[id]" class="form-control required" />
                        </div>
                    </div>
                    <div class="input-box">
                        <label for="bank" class="col-form-label"><?php echo $this->translate('Bank of Deposit') ?></label>
                        <div class="cell">
                            <input type="text" id="bank" name="detail[bank]" data-base="{'#type':'1'}" class="form-control required" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-theme">
                        <?php echo $this->translate('Bind') ?>
                    </button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                        <?php echo $this->translate('Cancel') ?>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
