<?php
if ($this->getSegment('customer')->get('hasLoggedIn')):
    $config = $this->getConfig();
    ?>
    <form action="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/save/') ?>" method="post" data-upload="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/upload/') ?>">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="category_id" value="<?php echo $this->getVariable('category_id', '') ?>" />
        <input type="hidden" name="product_id" value="<?php echo $this->getVariable('product_id', $this->getQuery('product_id', '')) ?>" />
        <div class="fieldset">
            <div class="input-box">
                <label for="post:title" class="col-form-label required"><?php echo $this->translate('Title') ?></label>
                <div class="cell">
                    <input type="text" name="title" id="post:title" class="form-control required" />
                </div>
            </div>
            <div class="input-box">
                <label for="post:content" class="col-form-label required"><?php echo $this->translate('Content') ?></label>
                <div class="cell">
                    <textarea name="content" id="post:content" class="form-control required<?php if ($config['forum/post/wysiwyg']): ?> htmleditor fullbar<?php endif ?>"></textarea>
                </div>
            </div>
            <?php if ($config['forum/post/captcha']): ?>
                <div class="input-box">
                    <label for="post:captcha" class="col-form-label"><?php echo $this->translate('Captcha') ?></label>
                    <div class="cell">
                        <input type="text" name="captcha" class="form-control required captcha" maxlength="5" id="post:captcha" autocomplete="off" spellcheck="false" data-rule-remote="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/validCaptcha/') ?>" />
                        <img src="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/captcha/') ?>" alt="" class="captcha" height="26" width="70" />
                    </div>
                </div>
            <?php endif ?>
            <div class="buttons-set">
                <button type="submit" class="btn btn-theme"><?php echo $this->translate('Submit') ?></button>
            </div>
        </div>
    </form>
<?php endif; ?>
