<?php
$poll = $this->getVariable('poll');
if($poll){
$config = $this->getConfig();
$exp = empty($poll['expired_at']) ? strtotime($poll['created_at']) + 86400 * $config['forum/post/expiration'] : strtotime($poll['expired_at']);
$date = date('Y-m-d', $exp);
if (!$this->getSegment('customer')->get('hasLoggedIn')):
    ?>
    <p class="required-login"><?php echo $this->translate('You have to vote after %sLogin/Register%s', ['<a href="' . $this->getBaseUrl('customer/account/login/?success_url=') . str_replace(['+', '/', '='], ['-', '_', ''], urlencode($this->getRequest()->getUri())) . '">', '</a>']) ?></p>
    <?php
elseif ($poll->voted() || time() >= $exp):
    $sum = count($poll->getVoters());
    ?>
    <h4 class="title pt-4">[<?php echo $this->translate('Vote') ?>]<?php echo $poll['title']; ?></h4>
    <ol class="poll" data-max-choices="<?php echo $poll['max_choices'] ?>">
        <?php
        $selected = $poll->getOptionsByCustomer();
        foreach ($poll->getOptions() as $option):
            $count = count($option->getVoters());
            ?>
            <li<?php if (in_array($option['id'], $selected)): ?> class="selected"<?php endif ?>>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $count ?>" aria-valuemin="0" aria-valuemax="<?php echo $sum ?>" style="width:<?php echo printf('%.8f', $count / $sum * 100) ?>%;"></div>
                </div>
                <div>
                    <?php echo $option['description'] ?>
                    <span class="percent">(<span class="count"><?php echo $count ?></span>/<span class="sum"><?php echo $sum ?></span>)</span>
                </div>
            </li>
        <?php endforeach ?>
    </ol>
    <p class="comment"><?php echo $this->translate('The poll would be closed at %s.', [$date]) ?></p>
<?php else: ?>
    <h4 class="title">[<?php echo $this->translate('Vote') ?>]<?php echo $poll['title']; ?></h4>
    <form action="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/vote/') ?>" method="post">
        <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
        <input type="hidden" name="poll_id" value="<?php echo $poll['id'] ?>" />
        <ol class="poll" data-max-choices="<?php echo $poll['max_choices'] ?>">
            <?php foreach ($poll->getOptions() as $option): ?>
            <li class="pt-2 align-items-center d-flex">
                    <input type="<?php echo $poll['max_choices'] > 1 ? 'checkbox' : 'radio' ?>" id="poll-<?php echo $option['id'] ?>" name="option_id[]" value="<?php echo $option['id'] ?>" class="required" />
                    <label for="poll-<?php echo $option['id'] ?>">&nbsp;<?php echo $option['description'] ?></label>
                </li>
            <?php endforeach ?>
        </ol>
        <p class="comment"><?php echo $this->translate('Only %d option(s) could be chosen at most.', [$poll['max_choices']]), ', ', $this->translate('The poll would be closed at %s.', [$date]) ?></p>
        <div class="buttons-set">
            <button type="submit" class="btn btn-primary"><?php echo $this->translate('Vote') ?></button>
        </div>
    </form>
<?php 
endif;
}
?>
