<?php
$shipment = $this->getShipment();
$order = $this->getOrder();
$currency = $order->getCurrency();
$tracks = $this->getTrack();
?>
<div class="view clearfix">
    <div class="buttons-set text-end">
        <a href="<?php echo $this->getAdminUrl('sales_shipment/print/?id=' . $order->getId()) ?>" class="btn btn">
            <?php echo $this->translate('Print', [], 'sales') ?>
        </a>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipment Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate('ID'), ': ', $shipment['increment_id'] ?><br />
            <?php echo $this->translate('Order ID'), ': <a href="'.$this->getAdminUrl('sales_order/view/?id=' .$order['id']).'">', $order['increment_id'],'</a>' ?><br />
            <?php
            if ($store = $order->getStore()) {
                echo $this->translate('Store'), ': ', $store->offsetGet('name');
            }
            ?><br />
            <?php
            if ($language = $order->getLanguage()) {
                echo $this->translate('Language'), ': ', $language->offsetGet('name');
            }
            ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Customer Infomation', [], 'sales') ?></h4>
        </div>
        <div class="panel-body"><?php if ($customer = $this->getCustomer()): ?>
                ID: <?php echo $customer->getId() ?><br />
                <?php echo $this->translate('Username'), ': ', $customer['username'] ?>
            <?php endif ?></div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('shipping_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Billing Address', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo nl2br($order->offsetGet('billing_address')) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Shipping Method', [], 'sales') ?></h4>
        </div>
        <div class="panel-body">
            <?php echo $this->translate($order->getShippingMethod()->getLabel()) ?>
        </div>
    </div>
    <div class="panel">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Comment') ?></h4>
        </div>
        <div class="panel-body"><?php echo $shipment['comment'] ?></div>
    </div>
    <div class="panel wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Product(s)') ?></h4>
        </div>
        <div class="panel-body grid table-responsive">
            <table class="table table-hover table-striped table-no-border">
                <thead class="sort-by">
                    <tr>
                        <th><?php echo $this->translate('Product Name', [], 'sales') ?></th>
                        <th><?php echo $this->translate('SKU', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Options', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Price', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Qty', [], 'sales') ?></th>
                        <th><?php echo $this->translate('Total', [], 'sales') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->getCollection() as $item): ?>
                        <tr<?php if (isset($item['id'])): ?> data-id="<?php echo $item['id'] ?>"<?php endif ?>>
                            <td><?php echo $item['product_name'] ?></td>
                            <td><?php echo $item['sku'] ?></td>
                            <td>
                                <?php
                                $options = json_decode($item['options'], true);
                                if ($item['product_id'] && count($options)) {
                                    foreach ($item['product']->getOptions() as $option) {
                                        if (isset($options[$option->getId()])) {
                                            echo $option['title'], ': ', (in_array($option['input'], ['select', 'radio', 'checkbox', 'multiselect']) ?
                                                    $option->getValue($options[$option->getId()]) : $options[$option->getId()]), '<br />';
                                        }
                                    }
                                }
                                ?>
                            </td>
                            <td><?php echo $currency->format($item['price']) ?></td>
                            <td><?php echo $item['qty'] ?></td>
                            <td><?php echo $currency->format($item['total']) ?></td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="panel wide">
        <div class="panel-heading">
            <h4 class="panel-title"><?php echo $this->translate('Tracking', [], 'sales') ?></h4>
        </div>
        <div class="panel-body carrier">
            <?php if (count($tracks)): ?>
                <table class="table table-hover table-striped">
                    <?php
                    foreach ($tracks->toArray() as $track):
                        if ($track['description']):
                            ?>
                            <tr>
                                <td><?php echo $track['description'] ?></td>
                                <td><?php echo $track['created_at'] ?></td>
                            </tr>
                            <?php
                        endif;
                    endforeach;
                    ?>
                </table>
            <?php endif ?>
            <form action="<?php echo $this->getAdminUrl('sales_shipment/track/') ?>" method="post">
                <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                <input type="hidden" name="shipment_id" value="<?php echo $shipment['id'] ?>" />
                <input type="hidden" name="order_id" value="<?php echo $order['id'] ?>" />
                <input type="hidden" name="schedule" id="schedule" value="<?php echo count($tracks) ? 0 : 1 ?>" />
                <div class="input-box">
                    <label for="carrier-code" class="control-label"><?php echo $this->translate('Carrier', [], 'sales') ?></label>
                    <select name="carrier_code" id="carrier-code" class="form-control" onchange="$('#schedule').val(1);">
                        <option value=""><?php echo $this->translate('Custom Carrier') ?></option>
                        <?php foreach ($this->getCarriers() as $code => $title): ?>
                            <option value="<?php echo $code ?>" title="<?php echo $title ?>"<?php if(isset($track) && $track['carrier_code'] === $code): ?> selected="selected"<?php endif ?>><?php echo $this->translate($title, [], 'shipping') ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="input-box">
                    <label for="carrier" class="control-label"><?php echo $this->translate('Title') ?></label>
                    <input type="text" name="carrier" class="form-control" id="carrier" maxlength="32" value="<?php echo $track['carrier'] ?? '' ?>" />
                </div>
                <div class="input-box">
                    <label for="number" class="control-label"><?php echo $this->translate('Tracking Number', [], 'sales') ?></label>
                    <input type="text" class="form-control" name="tracking_number" id="number" value="<?php echo $track['tracking_number'] ?? '' ?>" />
                </div>
                <?php if (count($tracks)): ?>
                    <input type="hidden" name="carrier-code" value="" />
                    <div class="input-box">
                        <label for="description" class="control-label"><?php echo $this->translate('Description', [], 'sales') ?></label>
                        <textarea class="form-control required" id="description" name="description"></textarea>
                    </div>
                    <div class="input-box">
                        <label for="created-at" class="control-label"><?php echo $this->translate('Description', [], 'sales') ?></label>
                        <input type="datetime" class="form-control" id="created-at" name="created_at" value="<?php echo date('Y-m-d H:i:s') ?>" />
                    </div>
                <?php endif ?>
                <div class="buttons-set text-end">
                    <button type="submit" class="btn btn-theme"><?php echo $this->translate('Submit') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
