<div class="container-fluid">
    <div class="container">
        <div class="row mt-5 d-flex">
            <div class="text-center w-100"><h1>会员等级体系，订制专享优惠</h1></div>
            <div class="text-center w-100 p-5"><a href="/customer/account/login/" type="button" class="btn btn-danger">开通会员</a></div>
            <div class="col-4 p-2">
                <div style="background-color:#0099CC;color: #fff" class="rounded text-center pb-4 pt-4">
                    <h4>全场折扣</h4>
                    <p>VIP会员全场6折购</p>
                    <p class="font-32"><span class="fa fa-vcard"></span></p>
                </div>
            </div>
            <div class="col-4 p-2">
                <div style="background-color:#0099CC;color: #fff" class="rounded text-center pb-4 pt-4">
                    <h4>终身会员</h4>
                    <p>员享受更多福利</p>
                    <p class="font-32"><span class="fa fa-vcard"></span></p>
                </div>
            </div>
            <div class="col-4 p-2">
                <div style="background-color:#0099CC;color: #fff" class="rounded text-center pb-4 pt-4">
                    <h4>分享返佣</h4>
                    <p>三级分销返佣计划，赚钱了赚钱了！</p>
                    <p class="font-32"><span class="fa fa-vcard"></span></p>
                </div>
            </div>
        </div>
        <div class="text-center w-100 p-5">&nbsp;</div>
    </div>
</div>
