<?php
$item = $this->getVariable('item');
$key = $this->getVariable('key');
$id = trim(preg_replace('/\W+/', '-', $key), '-');
$parent = $this->getVariable('parent');
//var_dump($item);
//exit;
?>
<div class="input-box <?php echo isset($item['containerclass'])?$item['containerclass']:'' ?> <?php echo $this->getVariable('boxClass') ?>">
    <?php if (isset($item['label'])): ?>
        <label for="<?php echo $id ?>" class="control-label <?php echo isset($item['labelclass'])?$item['labelclass']:'' ?> <?php if (isset($item['required'])): ?> required<?php endif ?>">
            <?php echo $this->translate($item['label']) ?>
        </label>
    <?php endif ?>
    <div class="cell">
        <select name="<?php echo $key ?>" id="<?php echo $id ?>"<?php if (!empty($item['value'])): ?> data-default-value='<?php echo is_array($item['value']) ? json_encode($item['value']) : $item['value'] ?>'<?php
        endif;
        if (!isset($item['attrs']['class'])):
            ?> class="form-control  <?php if (isset($item['required'])): ?> required<?php endif ?> <?php
                    if (isset($item['class'])) {
                        echo $item['class'];
                    }
                    ?>"<?php endif ?> <?php
                if (isset($item['attrs'])) {
                    echo $parent->getAttrs($item['attrs']);
                }
                ?> data-msg-required="<?php echo $this->translate('Please choose ').(isset($item['label'])?$item['label']:$key);?>">
                    <?php if (empty($item['required']) && !isset($item['attrs']['multiple'])): ?>
                <option value=""><?php echo $this->translate($item['empty_string'] ?? 'Please Select') ?></option>
            <?php endif ?>
            <?php
            if (!empty($item['options'])):
                
                foreach ($item['options'] as $value => $label):
                ?>
               <option value="<?php echo $label['id'] ?>"<?php if (isset($item['value']) && $item['value'] !== '' && (in_array($label['id'], (array) $item['value']) || (string) $label['id'] === $item['value'])): ?> selected="selected"<?php endif ?>><?php echo str_repeat('&nbsp;&nbsp;',$label['level']).'|-- '.$this->translate($label['name']) ?></option>
                    
                <?php endforeach ?>
            <?php endif ?>
        </select>
        <?php if(isset($item['attrs']['multiple'])): ?>
            <a href="javascript:void(0);" onclick="javascript:$('select#<?php echo $id ?>').val('');" class="clear"><?php echo $this->translate('Clear') ?></a>
        <?php endif ?>
        <?php if (isset($item['comment'])): ?>
            <div class="comment">
                <?php echo nl2br($this->translate($item['comment'])) ?>
            </div>
        <?php endif ?>
    </div>
</div>
