<?php
$products = $this->getProducts();
$class = $this->getVariable('class');
if (count($products)):
    ?>
    <div class="product-link">
        <?php if ($this->getVariable('title')): ?>
            <h4 class="title mb-2 mb-md-4 mt-2 mt-md-5">
                <span><?php echo $this->translate($this->getVariable('title')) ?></span>
            </h4>
        <?php endif ?>
        <ul class="d-flex">
            <?php
            foreach ($products as $product):
                $thumbnail = $product->getThumbnail();
                ?>
                <li class="item <?php echo $class;?>">
                    <a href="<?php echo $product->getUrl() ?>" title="<?php echo $product['name'] ?>" class="product-image">
                        <img loading="lazy" src="<?php echo $thumbnail ?>" alt="<?php echo $product['name'] ?>" />
                    </a>
                    <h6 class="product-name">
                        <a href="<?php echo $product->getUrl() ?>">
                            <?php echo $product['name'] ?>
                        </a>
                    </h6>
                    <div class="price-box">
                        <?php echo $this->getPriceBox($product) ?>
                    </div>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <?php
else:
    return false;
    ?>
<?php endif; ?>
