<?php
$config = $this->getConfig();
$new = strtotime('-' . $config['forum/post/new_days'] . 'days');
$current = $this->getSegment('customer')->get('hasLoggedIn') ? $this->getSegment('customer')->get('customer')['id'] : 0;
$posts = $this->getPosts();
if (!empty($posts)):
    foreach ($posts as $post):
        if ($post['is_draft'] != 1):
            $thumbnail = $post->getThumbnail();
            $links = $post->getLinks();
            $linksa = '';
            if (count($links) > 0) {
                for ($l = 0; $l < count($links); $l++) {
                    $linksa .= '&nbsp;<a href="' . $links[$l]["link"] . '" class="sys-blue sys-underline">' . $links[$l]["name"] . '</a>';
                }
            }
            $customer = $post->getCustomer();
            ?><li class="item col-6 col-sm-4 col-md-3<?php if ($post['poll_id']): ?> poll<?php
            endif;
            if (strtotime($post['created_at']) >= $new):
                ?> new<?php
                endif;
                if (strtotime($post['is_hot']) >= $new):
                    ?> hot<?php endif; ?>" > 
                <div class="item-list">
                    <a data-href="<?php echo $this->getBaseUrl('forum/post/json/?id=' . $post["id"]); ?>" class="product-image">
                        <img loading="lazy" src="<?php echo $thumbnail ? $this->getUploadedUrl('forum/' . $thumbnail) : $this->getPubUrl('frontend/images/placeholder.png'); ?>" />                            
                    </a>
                    <div class="product-text">
                        <h6 class="product-name"><a href="<?php echo $post->getUrl() ?>" title="<?php echo $post['title'] ?>"><?php echo mb_substr($post['title'], 0, 20, 'utf-8') ?></a> <?php echo $linksa; ?></h6>
                        <div class="product-user">
                            <a href="<?php echo $this->getBaseUrl("forum/space/?customer_id=" . $customer['id']) ?>"><img class="rounded-circle" src="<?php echo!empty($customer['avatar']) ? $this->getUploadedUrl('customer/avatar/' . $customer['avatar']) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" alt="<?php echo $customer['username'] ?>" /></a>
                            <span class="product-userName"><a href="<?php echo $this->getBaseUrl("forum/space/?customer_id=" . $customer['id']) ?>"><?php echo $customer['username'] ?></a></span>

                            <?php
                            if ($this->getSegment('customer')->get('hasLoggedIn')):
                                if ($current == $post['customer_id']):
                                    ?>
                                    <a href="#" class="product-heart" name="<?php echo $post['id'] ?>" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>">
                                        <i class="fa fa-heart" aria-hidden="true" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"></i>
                                        <span class="number" id="number" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"><?php echo $post['like']; ?></span>
                                    </a>
                                    <?php
                                else:
                                    ?>
                                    <?php
                                    if ($post['liked'] > 0):
                                        ?>
                                        <a href="#" class="product-heart" name="<?php echo $post['id'] ?>" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>">
                                            <i class="fa fa-heart" aria-hidden="true" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"></i>
                                            <span class="number" id="number" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"><?php echo $post['like']; ?></span>
                                        </a>
                                        <?php
                                    else:
                                        ?>
                                        <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like product-heart" name="<?php echo $post['id'] ?>" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>">
                                            <i class="fa fa-heart-o" aria-hidden="true" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"></i>
                                            <span class="number" id="number" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"><?php echo $post['like']; ?></span>
                                        </a>
                                    <?php
                                    endif;
                                    ?>
                                <?php
                                endif;
                                ?>
                                <?php
                            else:
                                ?>
                                <a href="<?php echo $this->getBaseUrl('customer/account/logion/') ?>" class="like product-heart">
                                    <i class="fa fa-heart-o" aria-hidden="true" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"></i>
                                    <span class="number" title="<?php echo $this->translate('Likes: %d', [$post['like']]); ?>"><?php echo $post['like']; ?></span>
                                </a>
                            <?php
                            endif;
                            ?>
                            <reviews-button
                                postId="<?php echo $post['id']; ?>"
                                title="<?php echo $this->translate('Total %s Comments', [$post['reviews']]) ?>"
                                count="<?php echo ($post['reviews'] > 0 ? $post['reviews'] : ''); ?>"
                                ></reviews-button>
                                <?php
                                /*
                                  <span class="views"><?php echo $this->translate('Views: %d', [$post['views']]) ?></span>
                                  <span class="reviews"><?php echo $this->translate('Reviews: %d', [$post['reviews']]) ?></span>
                                  <span class="date"><?php echo $this->getTime($post['created_at']) ?></span>
                                 */
                                ?>

                        </div>
                        <div><?php
                            if (!empty($post['tags'])) {
                                foreach (explode(",", $post['tags']) as $tag) {
                                    echo "<span style='background-color:#f5f4f4;display:inline-block;margin:5px; padding:5px;border-radius:5px;'>" . $tag . "</span>";
                                }
                            }
                            ?></div>
                    </div>
                </div>
            </li>
            <?php
        endif;
    endforeach;
else:
    ?>
    <p class="empty text-center"><?php echo $this->translate('No post available right now.'); ?></p>
<?php
endif;
?>

