<?php
$customerList = $this->getCustomer();
foreach ($customerList as $value):
    ?> 
    <dd style="border-bottom: 1px #ddd dashed">
        <div class="d-flex col-12" style="padding: 8px 0; justify-content: space-between;align-items: center;">
            <div class="d-flex">
                <div><a href="<?php echo $this->getBaseUrl('forum/space/?customer_id='.$value['id']); ?>"><img src="<?php echo $value['avatar'] ? $this->getUploadedUrl('pub/upload/customer/avatar/' . $value['avatar']) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" alt="<?php echo $value['username']; ?>" class="small-img rounded-circle" /></a></div>
                <div>
                    <p class="font-12" style="word-wrap:break-word;margin: 0;padding: 0;"><a href="<?php echo $this->getBaseUrl('forum/space/?customer_id='.$value['id']); ?>"><?php echo mb_substr($value['username'], 0, 24, 'UTF8') . (mb_strlen($value['username']) > 24 ? '...' : ''); ?></a></p>
                    <p class="user-Similar font-12" style="word-wrap:break-word;margin: 0;padding: 0">
                        <?php
                        echo $this->translate('To subscribe');
                        ?> 
                    </p>
                </div>
            </div>
            <div>
                <?php
                if ($value['meFollowed'] > 0) {
                    ?>
                    <a href="<?php echo $this->getBaseUrl('forum/space/?customer_id='.$value['id']) ?>" class="btn-secondary font-14"><?php echo $this->translate('Subscribed'); ?></a>
                    <?php
                } else {
                    ?>
                    <a href="<?php echo $this->getBaseUrl('forum/account/like/') ?>" class="attention-btn font-14" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $value['id']; ?>"><?php echo $this->translate('To subscribe'); ?></a>
                    <?php
                }
                ?>
            </div>
        </div>
    </dd>
    <?php
endforeach;
?>

