<?php
$collection = $this->getVariable("collection");
$query = $this->getVariable("query");
?>
<table class="table table-hover table-striped table-no-border">
    <colgroup>
        <col width="1" />
        <col width="1" />
        <col />
        <col width="1" />
        <col width="1" />
    </colgroup>
    <thead class="sort-by">
        <tr>
            <th class="checkbox">&nbsp;</th>
            <th>ID</th>
            <th class="text-start"><?php echo $this->translate('Name') ?></th>
            <th><?php echo $this->translate('SKU') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($collection as $item):
            ?>
            <tr data-id="<?php echo $item['id'] ?>">
                <td class="text-center checkbox">
                    <input type="radio" id="productradio-<?php echo $item['id'] ?>" name="productradio" value="<?php echo $item['id'] ?>"<?php if (in_array($item['id'], $this->getActiveIds())): ?> checked="checked"<?php endif ?> />
                </td>
                <td><?php echo $item['id'] ?></td>
                <td class="text-start"><label for="productradio-<?php echo $item['id'] ?>"><?php echo $item['name'] ?></label></td>
                <td class="text-nowrap"><?php echo $item['sku'] ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
    <tfoot>
        <tr>
            <td class="checkbox">
                &nbsp;
            </td>
            <td colspan="4" class="text-end">
                <?php
                if (is_object($collection)) {
                    echo $this->getChild('pager')->setCollection($collection);
                }
                ?>
            </td>
        </tr>
    </tfoot>
</table>
