<?php
$id = $this->getQuery();
$customer_id = intval($id['customer_id']);
$config = $this->getConfig();
$current = $this->getSegment('customer')->get('hasLoggedIn') ? intval($this->getSegment('customer')->get('customer')['id']) : 0;
$customer = new Redseanet\Customer\Model\Customer;
$username = $customer->load($customer_id);
$posts = $this->getPosts();
$follows = $this->getFollowCount();
$fans = $this->getFansCount();
$belikes = $this->getBelikeCount();
$befollows = $this->getBefollowCount();
$followed = false;
if ($current != 0) {
    if ($username['id'] == $current) {
        $followed = true;
    } else {
        if ($this->customerFollowed($current, $customer_id)) {
            $followed = true;
        }
    }
}
$is_json = $this->getVariable('is_json');
if ($is_json) {
    ?>  
    <?php
    if (count($posts)):
        foreach ($posts as $post):
            $thumbnail = $post->getThumbnail();
            ?>
            <li class="item  col-6 col-md-4">
                <div class="item-list">
                    <div class="dropdown text-end">
                        <a id="dLabel" data-target="#" href="#" class="ellipsis-btn" data-bs-toggle="dropdown" aria-expanded="false" role="button" aria-haspopup="true">
                            <span class="fa fa-ellipsis-h" aria-hidden="true"></span>
                        </a>
                        <dl class="dropdown-menu">
                            <dt><a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/collect/') ?>" class="collect" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>"><?php echo $this->translate('Favorites') ?></a></dt>
                        </dl>
                    </div>
                    <a href="<?php echo $post->getUrl() ?>" class="product-image">
                        <img src="<?php echo $thumbnail ? $this->getBaseUrl('pub/upload/forum/' . $thumbnail) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg'); ?>" alt="" loading="lazy">
                    </a>
                    <div class="product-text">
                        <h6 class="product-name">
                            <a href="<?php echo $post->getUrl() ?>"><?php echo $post['title'] ?></a>
                        </h6>
                        <div class="product-user d-flex align-items-center justify-content-between">
                            <span class="product-userName">
                                <img src="<?php echo $username['avatar'] ? $this->getBaseUrl('pub/upload/customer/avatar/' . $username['avatar']) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" class="rounded-circle user-titleImg " />
                                <?php echo $username['username'] ?>
                            </span>
                            <span class="publish-time"><?php echo $this->getTime($post['created_at']) ?></span>
                            <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like product-heart" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>">
                                <i class="fa fa-heart-o" aria-hidden="true"></i>
                                <span><?php echo $post['like'] ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
            <?php
        endforeach;
    endif;
} else {
    ?>
    <div class="container userSpace-main">
        <div class="container">
            <div class="background-white col-12">
                <div class="userSpace-head">
                    <div class="userSpace-headBg">
                        <div class="userSpace-head_content">
                            <span>
                                <img src="<?php echo $username['avatar'] ? $this->getUploadedUrl('customer/avatar/' . $username['avatar']) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" class="rounded-circle user-titleImg" />
                                <span class="user-plus">
                                    <?php
                                    if ($current == 0) {
                                        ?>
                                        <a href="<?php echo $this->getBaseUrl('customer/account/logion/') ?>" class="attention-btn"><?php echo $this->translate('To subscribe'); ?></a>
                                        <?php
                                    } else {
                                        if (!$followed) {
                                            ?>
                                            <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/account/like/') ?>" class="attention-btn" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $username['id']; ?>"><?php echo $this->translate('To subscribe'); ?></a>
                                            <?php
                                        } else {
                                            ?>
                                            <a class="attention-btn"><?php echo $this->translate('Subscribed'); ?></a>
                                            <?php
                                        }
                                    }
                                    ?>
                                </span>
                            </span>
                            <h5 class="user-name"><?php echo $username['username'] ?></h5>
                            <h6><?php echo $username['motto'] ?></h6>
                        </div>
                        <div class="userSpace-link col-12 row">
                            <ul class="col-12 col-md-12 col-sm-12 d-flex">
                                <li class="col-3">
                                    <a href="" class="a-block">
                                        <p class="h5">
                                            <?php echo $follows; ?>
                                        </p>
                                        <p class="h5">
                                            <?php echo $this->translate('Subscribed'); ?>
                                        </p>
                                    </a>
                                </li>
                                <li class="col-3">
                                    <a href="">
                                        <p class="h5">
                                            <?php echo $fans; ?>
                                        </p>
                                        <p class="h5">
                                            <?php echo $this->translate('Fans'); ?>
                                        </p>
                                    </a>
                                </li>
                                <li class="col-3">
                                    <a href="">
                                        <p class="h5">
                                            <?php echo $belikes ?>
                                        </p>
                                        <p class="h5">
                                            <?php echo $this->translate('Be Like'); ?>
                                        </p>
                                    </a>
                                </li>
                                <li class="col-3">
                                    <a href="">
                                        <p class="h5">
                                            <?php echo $befollows ?>
                                        </p>
                                        <p class="h5">
                                            <?php echo $this->translate('Be Collected'); ?>
                                        </p>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="publish-content col-12">
                    <div class="grid masonry-container mt-4">
                        <ul class="products-grid masonry clearfix" id="masonry" data-url="<?php echo $this->getBaseUrl(); ?>forum/space/?customer_id=<?php echo $customer_id; ?>&is_json=true">
                            <?php
                            if (count($posts)):
                                foreach ($posts as $post):
                                    $thumbnail = $post->getThumbnail();
                                    ?>
                                    <li class="item  col-6 col-md-4">
                                        <div class="item-list">
                                            <div class="dropdown text-end">
                                                <a id="dLabel" data-target="#" href="#" class="ellipsis-btn" data-bs-toggle="dropdown" aria-expanded="false" role="button" aria-haspopup="true">
                                                    <span class="fa fa-ellipsis-h" aria-hidden="true"></span>
                                                </a>
                                                <dl class="dropdown-menu">
                                                    <dt><a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/collect/') ?>" class="collect" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>"><?php echo $this->translate('Favorites') ?></a></dt>
                                                </dl>
                                            </div>
                                            <a href="<?php echo $post->getUrl() ?>" class="product-image">
                                                <img src="<?php echo $thumbnail ? $this->getBaseUrl('pub/upload/forum/') . $thumbnail : $this->getPubUrl('frontend/images/placeholder.png'); ?>" alt="" class="bttrlazyloading">
                                            </a>
                                            <div class="product-text">
                                                <h6 class="product-name">
                                                    <a href="<?php echo $post->getUrl() ?>"><?php echo $post['title'] ?></a>
                                                </h6>
                                                <div class="product-user d-flex align-items-center justify-content-between">
                                                    <span class="product-userName">
                                                        <img src="<?php echo $username['avatar'] ? $this->getBaseUrl('pub/upload/customer/avatar/') . $username['avatar'] : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" class="rounded-circle user-titleImg " />       
                                                        <?php echo $username['username'] ?>
                                                    </span>
                                                    <span class="publish-time"><?php echo $this->getTime($post['created_at']) ?></span>
                                                    <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like product-heart" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post->getId() ?>">
                                                        <i class="fa fa-heart-o" aria-hidden="true"></i>
                                                        <span><?php echo $post['like'] ?></span>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <?php
                                endforeach;
                            else:
                                ?>
                                <p class="text-center"><?php echo $this->translate('The current user has not posted a post for the time being.'); ?></p>
                            <?php
                            endif;
                            ?>
                        </ul>
                    </div>
                    <div class="main-end col-12">
                        <span class="end-text">END</span>
                    </div>
                </div>

            </div>
        </div>
    </div>
<?php } ?>