<?php
$this->clearNewFansCount();
$config = $this->getConfig();
$fans = $this->getFans();
?>
<div class="draft-cont  linked-cont fanList-cont">
    <ul class="col-12 row">
        <?php
        if (count($fans)):
            foreach ($fans as $fan):
                ?>
                <li class="col-md-6 col-sm-6 col-12">
                    <div class="draft-list product-user watchlist-listBox">
                        <div class="text-end">
                            <span class="publish-time"><?php echo $this->getTime($fan['created_at']) ?></span>

                        </div>
                        <div class="col-12 linked-user">
                            <div class="inline-bolck linked-userImg">
                                <a href="<?php echo $this->getBaseUrl('forum/space/?customer_id=') . $fan['customer_id']; ?>">
                                    <img src="<?php echo $fan['avatar'] ? $this->getUploadedUrl('customer/avatar/') . $fan['avatar'] : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" alt="<?php echo $fan['username']; ?>">
                                </a>
                            </div>

                            <div class="product-text2 linked-userName col-10 ">
                                <p class="col-12 inline-bolck">
                                    <a href="#" class="fan-name"><?php echo $fan['username']; ?></a>
                                    <a href="#" class="padding-0"><?php echo $this->translate('Subscribe Me'); ?></a>
                                </p>
                            </div>
                            <p class="col-12 padding-30 linked-link"><?php echo $fan['motto'] ?></p>
                        </div>
                        <div class="text-end">
                            <a href="<?php echo $this->getBaseUrl('forum/space/?customer_id=') . $fan['customer_id']; ?>" class="btn btn-secondary color-c6 publish-btn float-end"><?php echo $this->translate('View'); ?></a>
                        </div>
                    </div>
                </li>
                <?php
            endforeach;
        else:
            ?>
            <p class="empty text-center"><?php echo $this->translate('No post available right now.') ?></p>
        <?php
        endif;
        ?>
    </ul>
</div>
