<?php
$config = $this->getConfig();
$new = strtotime('-' . $config['forum/post/new_days'] . 'days');
$favorites = $this->getFavoritedWithPosts();
$is_json = $this->getVariable('is_json');
$current = $this->getSegment('customer')->get('hasLoggedIn') ? $this->getSegment('customer')->get('customer')['id'] : 0;
if ($is_json){
    if (count($favorites)):
        foreach ($favorites as $post):
        $thumbnail = $post->getThumbnail();
            ?>
            <li class="item col-6 col-sm-4 col-md-4<?php if ($post['poll_id']): ?> poll<?php
            endif;
            if (strtotime($post['created_at']) >= $new):
                ?> new<?php
                endif;
                if (strtotime($post['is_hot']) >= $new):
                    ?> hot<?php endif ?>">
                <div class="item-list">
                    <div class="dropdown text-end">
                        <a id="dLabel" data-target="#" href="#" class="ellipsis-btn" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="fa fa-ellipsis-h" aria-hidden="true"></span>
                        </a>
                        <dl class="dropdown-menu">
                            <dt>
                                <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/social/beCollectedRemove/') ?>" class="close-btn" data-method="delete" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post["id"] ?>">
                                    <i class="fa fa-close" aria-hidden="true"></i>
                                    <?php echo $this->translate('Delete') ?>
                                </a>
                            </dt>
                        </dl>
                    </div>
                    <a href="<?php echo $post->getUrl() ?>" class="product-image">
                        <img src="<?php echo $thumbnail ? $this->getUploadedUrl('forum/' . $thumbnail) : $this->getPubUrl('frontend/images/placeholder.png'); ?>" />
                    </a>
                    <div class="product-text">
                        <h6 class="product-name"><a href="<?php echo $post->getUrl() ?>"><?php echo $post['title'] ?></a></h6>
                        <div class="product-user">
                            <a href="<?php echo $this->getBaseUrl('forum/space/?customer_id=') . $post['customer_id']; ?>"><img class="rounded-circle" src="<?php echo $post['avatar'] ? $this->getUploadedUrl('customer/avatar/' . $post['avatar']) : $this->getPubUrl('frontend/images/avatar-holderplace.jpg') ?>" alt="<?php echo $post['username'] ?>"></a>
                            <span class="product-userName">
                                <?php echo $post['username'] ?>
                                <span class="publish-time"><?php echo $this->getTime($post['created_at']); ?></span>
                            </span>
                            <?php if ($current): ?>
                                <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like product-heart" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post["id"] ?>" class="product-heart">
                                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                                    <span><?php echo $post['like']; ?></span>
                                </a>
                                <?php
                            else:
                                ?>
                                <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post["id"] ?>" class="product-heart">
                                    <i class="fa fa-heart-o" aria-hidden="true"></i>
                                    <span><?php echo $post['like']; ?></span>
                                </a>
                            <?php
                            endif;
                            ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php
        endforeach;
    endif;
}else{
    ?>
    <div class="grid masonry-container">
        <ul  class="products-grid masonry clearfix" id="masonry" data-url="<?php echo $this->getBaseUrl(); ?>forum/social/favoritedList/?is_json=true">
            <?php
            if (count($favorites)):
                foreach ($favorites as $post):
                $thumbnail = $post->getThumbnail();
                    ?>
                    <li class="item col-6 col-sm-4 col-md-4<?php if ($post['poll_id']): ?> poll<?php
                    endif;
                    if (strtotime($post['created_at']) >= $new):
                        ?> new<?php
                        endif;
                        if (strtotime($post['is_hot']) >= $new):
                            ?> hot<?php endif ?>">
                        <div class="item-list">
                            <div class="dropdown text-end">
                                <a id="dLabel" data-target="#" href="#" class="ellipsis-btn" data-bs-toggle="dropdown" aria-expanded="false" role="button" aria-haspopup="true">
                                    <span class="fa fa-ellipsis-h" aria-hidden="true"></span>
                                </a>
                                <dl class="dropdown-menu">
                                    <dt>
                                        <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/social/favoritedRemove/') ?>" class="close-btn" data-method="delete" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post["favorite_id"] ?>">
                                            <i class="fa fa-close" aria-hidden="true"></i>
                                            <?php echo $this->translate('Delete') ?>
                                        </a>
                                    </dt>
                                </dl>
                            </div>
                            <a href="<?php echo $post->getUrl() ?>" class="product-image">
                                <img src="<?php echo $thumbnail ? $this->getUploadedUrl('forum/' . $thumbnail) : $this->getPubUrl('frontend/images/placeholder.png'); ?>" />
                            </a>
                            <div class="product-text">
                                <h6 class="product-name"><a href="<?php echo $post->getUrl() ?>"><?php echo $post['title'] ?></a></h6>
                                <div class="product-user">
                                    <a href="<?php echo $this->getBaseUrl('forum/space/?customer_id=') . $post['customer_id']; ?>"><img class="rounded-circle" src="<?php echo $post['avatar'] ? $this->getBaseUrl('customer/avatar/' . $post['avatar']) : $this->getPubUrl('frontend/images/placeholder.png') ?>" alt="<?php echo $post['username'] ?>"></a>
                                    <span class="product-userName">
                                        <?php echo $post['username'] ?>
                                        <span class="publish-time"><?php echo $this->getTime($post['created_at']); ?></span>
                                    </span>
                                    <?php if ($current): ?>
                                        <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like product-heart" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post["id"] ?>" class="product-heart">
                                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                                            <span><?php echo $post['like']; ?></span>
                                        </a>
                                        <?php
                                    else:
                                        ?>
                                        <a href="<?php echo $this->getBaseUrl($config['forum/general/uri_key'] . '/post/like/') ?>" class="like" data-method="post" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $post["id"] ?>" class="product-heart">
                                            <i class="fa fa-heart-o" aria-hidden="true"></i>
                                            <span><?php echo $post['like']; ?></span>
                                        </a>
                                    <?php
                                    endif;
                                    ?>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php
                endforeach;
            else:
                ?>
                <p class="empty text-center"><?php echo $this->translate('No post available right now.') ?></p>
            <?php
            endif;
            ?>
        </ul>
    </div>
<?php } ?>
