#https://docs.docker.com/samples/library/mysql/#connect-to-mysql-from-the-mysql-command-line-client
version: '3.5'
services:
  mysql:
    container_name: "mysql_c"
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    networks:
      redsea:
        ipv4_address: 172.19.11.2
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Testing%%2029
      MYSQL_DATABASE: redseanetshop
      MYSQL_USER: denny
      MYSQL_PASSWORD: Testing%%2029
      TZ: Asia/Shanghai
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_c
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql:rw
      - ./mysql/config/:/var/lib/mysql-files/
      - ./mysql/logs/:/var/log/mysql:rw
  redis:
    container_name: "redis_c"
    image: redis
    networks:
      redsea:
        ipv4_address: 172.19.11.3
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/logs/redis.log:/usr/local/redis/redis.log:rw
  nginx_c:
    container_name: "nginx_c"
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - RESTY_CONFIG_OPTIONS_MORE="--with-http_stub_status_module"
    networks:
      redsea:
        ipv4_address: 172.19.11.4
    restart: always
    volumes:
      - ./../:/var/www/html/:rw
      - ./nginx/config/:/etc/nginx/:rw
      - ./nginx/logs/:/usr/local/nginx/logs/:rw
    links:
      - fastcgi_c:fastcgi_c
    ports:
      - 80:80
      - 443:443
  fastcgi_c:
    container_name: "fastcgi_c"
    build:
      context: .
      dockerfile: ./fastcgi/Dockerfile
    networks:
      redsea:
        ipv4_address: 172.19.11.5
    restart: always
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    volumes:
      - ./../:/var/www/html/:rw
      - ./tmp/:/tmp/livechat/:rw
      - ./fastcgi/config/php.ini:/usr/local/etc/php/php.ini:rw
      - ./fastcgi/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./fastcgi/logs/:/var/log/php-fpm/:rw
    environment:
       PHP_FPM_PM_STATUS_PATH: "/status"
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq_c
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "123456"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./rabbitmq/config/data:/var/lib/rabbitmq/mnesia:rw
      - ./rabbitmq/config/:/etc/rabbitmq:rw
    networks:
      redsea:
        ipv4_address: 172.19.11.6
  fastcgimq_c:
    container_name: "fastcgimq_c"
    build:
      context: .
      dockerfile: ./fastcgimq/Dockerfile
    networks:
     redsea:
       ipv4_address: 172.19.11.7
    restart: always
    command: /bin/bash -c "php /var/www/html/cli/RabbitMp.php"
    volumes:
      - ../:/var/www/html/:rw
      - ./fastcgimq/config/php.ini:/usr/local/etc/php/php.ini:rw
      - ./fastcgimq/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./fastcgimq/logs/:/var/log/php-fpm/:rw
networks:
  redsea:
    name: redsea
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
