<div class="message-box<?php if (!$this->getVariable('inline')): ?> container<?php endif ?>"><?php foreach ($this->getMessages() as $message): ?>
        <div class="alert alert-<?php echo $message['level'] ?? 'info' ?>">
            <?php echo is_scalar($message) ? $message : $message['message'] ?>
            <button type="button" class="btn" data-dismiss="alert">
                <span class="fa fa-fw fa-remove" aria-hidden="true"></span>
            </button>
        </div>
    <?php endforeach ?></div>
