<?php
$addresses = $this->getAddress();
$isVirtual = $this->getVariable('isVirtual');
$attributes = $this->getAddressAttribute();
?>
<input type="hidden" name="is_virtual" id="is_virtual" value="<?php echo $isVirtual ? 1 : 0; ?>" />
<?php
if (!$isVirtual):
    ?>
    <section class="section address">
        <h5 class="title"><?php echo $this->translate('Shipping Address') ?></h5>
        <ul class="list ps-0"><?php foreach ($addresses as $address): ?>
                <li data-id="<?php echo $address->getId() ?>" data-json='<?php echo json_encode($address->toArray()) ?>'  >
                    <input type="radio" name="shipping_address_id" id="shipping-address-<?php echo $address->getId() ?>" value="<?php echo $address->getId() ?>"<?php if ($address['is_default'] == 1): ?> checked="checked"<?php endif; ?> class="required" />
                    <label for="shipping-address-<?php echo $address->getId() ?>">
                        <?php echo $address->display() ?>
                    </label>
                    <?php if ($this->hasLoggedIn()): ?>
                        <?php if ($address->offsetGet('is_default') != 1): ?>
                            <a class="default" href="<?php echo $this->getBaseUrl('checkout/order/defaultAddress/?id='), $address->getId() ?>" class="default"><?php echo $this->translate('Set as Default') ?></span>
                            <?php else: ?>
                                <span class="btn-Address"><?php echo $this->translate('Default Address'); ?></span>
                            <?php endif ?>
                        <?php endif ?>
                        <a href="#modal-address" data-bs-target="div#modal-address" data-info='<?php echo json_encode($address) ?>' data-bs-toggle="modal" class="edit"><?php echo $this->translate('Edit') ?></a>
                        <a href="<?php echo $this->getBaseUrl('checkout/order/deleteaddress/') ?>" class="delete" data-method="delete" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id=<?php echo $address->getId() ?>"><?php echo $this->translate('Delete') ?></a>
                </li>
            <?php endforeach ?></ul>
        <template id="tmpl-address-list">
            <li data-id="{id}" data-json='{json}'>
                <input type="radio" name="shipping_address_id" id="shipping-address-{id}" value="{id}" />
                <label for="shipping-address-{id}">
                    {content}
                </label>
                <a href="javascript:void(0);" class="edit"><?php echo $this->translate('Edit') ?></a>
                <a href="<?php echo $this->getBaseUrl('checkout/order/deleteaddress/') ?>" class="delete" data-method="delete" data-params="csrf=<?php echo $this->getCsrfKey() ?>&id={id}"><?php echo $this->translate('Delete') ?></a>
            </li>
        </template>
        <?php //if ($this->hasLoggedIn()): ?>
            <button type="button" class="btn btn-add" data-info="{}" data-bs-toggle="modal" data-bs-target="div#modal-address"><?php echo $this->translate('Add New Address') ?></button>
        <?php //endif ?>
        <?php echo $this->getChild('addressmodal'); ?>
    </section>
<?php endif; ?>
