<?php
$attributes = $this->getAddressAttribute();
?>
<div class="modal fade" id="modal-address">
    <div class="modal-dialog">
        <div class="modal-content">
            <form action="<?php echo $this->getBaseUrl('checkout/order/saveaddress/') ?>" method="post" data-ajax="true">
                <div class="modal-header">
                    <h4 class="modal-title"><?php echo $this->translate('Address Infomation') ?></h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="csrf" value="<?php echo $this->getCsrfKey() ?>" />
                    <input type="hidden" name="id" />
                    <?php
                    foreach ($attributes as $attribute) {
                        $item = [
                            'type' => $attribute['input'],
                            'label' => $attribute['label']
                        ];
                        if ($attribute['is_required']) {
                            $item['required'] = 'required';
                        }
                        echo $this->getInputBox($attribute['code'], $item);
                    }
                    ?>
                    <script>
                        new Locate();
                    </script>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                    <button type="submit" class="btn btn-primary"><?php echo $this->translate('Save') ?></button>                       
                </div>
            </form>
        </div>
    </div>
</div>
