<?php
$sessions = $this->getSessions();
$current = $this->getVariable('current', false);
?>
<div id="livechat" class="clearfix sidebar">
    <form action="<?php echo $this->getWsUrl() ?>" id="chat-form">
        <img src="<?php echo empty($avatar = $this->getSegment('customer')->get('customer')['avatar']) ? $this->getPubUrl('frontend/images/avatar-holderplace.jpg') : $this->getUploadedUrl('customer/avatar/' . $avatar) ?>" id="avatar-0" class="img-fluid rounded-circle" alt="" />
        <button type="button" class="btn-nav collapsed" data-bs-toggle="collapse" data-target="#livechat-nav"><span class="fa fa-list-ul"></span></button>
        <div class="collapse" id="livechat-nav">
            <ul class="nav nav-pills flex-column" role="tablist">
                <?php
                foreach ($sessions as $session):
                    if (!$current) {
                        $current = $session['id'];
                    }
                    ?>
                    <li role="presentation"<?php if ($current == $session['id']): ?> class="active"<?php endif ?>>
                        <a href="#<?php echo $session['id'] ?>" role="tab" data-bs-toggle="tab" data-badge="0">
                            <?php echo $session['name'] ?>
                        </a>
                        <a href="<?php echo $this->getBaseUrl('livechat/index/close/') ?>" data-method="post" data-params="id=<?php echo $session['id'] ?>" class="close" title="<?php echo $this->translate('Close') ?>"><span class="fa fa-times"></span></a>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
        <?php if ($this->getSegment('customer')->get('hasLoggedIn')): ?>
            <input type="hidden" name="sender" value="<?php echo $this->getSegment('customer')->get('customer')['id'] ?>" />
        <?php endif ?>
        <div class="tab-content">
            <?php foreach ($sessions as $session): ?>
                <div role="tabpanel" class="tab-pane fade card<?php if ($current == $session['id']): ?> active in<?php endif ?>" id="<?php echo $session['id'] ?>">
                    <?php echo $this->getChild('chat')->setVariable('session', $session) ?>
                </div>
            <?php endforeach ?>
        </div>
    </form>
</div>
<button class="btn btn-livechat" type="button"><span class="fa fa-headphones"></span><span class="badge badge-pill" data-badge="0"></span></button>