<div class="fieldset credit-card">
    <label for="authorizenet-name" class="col-form-label"><?php echo $this->translate('Name on Card') ?></label>
    <input type="text" id="authorizenet-name" name="payment_data[name]" class="form-control required" autocomplete="off" spellcheck="false" disabled="disabled" data-msg-required="<?php echo $this->translate('Please enter name on card');?>!" />
    <label for="authorizenet-number" class="col-form-label"><?php echo $this->translate('Credit Card Number') ?></label>
    <div class="input-group">
   <input type="tel" data-type="credit-card" maxlength="51" id="authorizenet-number" name="payment_data[number]" class="form-control required cc-number" autocomplete="off" disabled="disabled" data-msg-required="<?php echo $this->translate('Please enter credit card number');?>!" />
    
  <div class="input-group-append">
      <span class="input-group-text" id="basic-addon2"><span class="credit-card-type"></span></span>
  </div>
</div>
   <label class="col-form-label"><?php echo $this->translate('Expiration Date') ?></label>
    <div class="d-flex">
      <div class="col-5">
        <select name="payment_data[exp_month]" class="form-control required" disabled="disabled" data-msg-required="<?php echo $this->translate('Please choose expiration month');?>!">
            <option value=""><?php echo $this->translate('Month') ?></option>
            <?php
            for ($month = 1; $month <= 12; $month++):
                ?>
                <option value="<?php echo $month ?>"><?php printf('%2d - %s', $month, $this->getMonth($month)) ?></option>
            <?php endfor ?>
        </select>
    </div>
        <div class="col-2 font-30 text-center">/</div>
    <div class="col-5">
        <select name="payment_data[exp_year]" class="form-control required" disabled="disabled" data-msg-required="<?php echo $this->translate('Please choose expiration year');?>!">
            <option value=""><?php echo $this->translate('Year') ?></option>
            <?php
            for ($year = $this->getYear(), $i = 0; $i < 15; $i++):
                ?>
                <option value="<?php echo $year + $i ?>"><?php echo $year + $i ?></option>
            <?php endfor ?>
        </select>
    </div>  
    </div>
    
    <label for="authorizenet-verification" class="col-form-label dropdown">
        <?php echo $this->translate('Card Verification Number') ?>(CVV)
        <a href="#" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="fa fa-info-circle" aria-hidden="true"></span>
            <span class="sr-only"><?php echo $this->translate('What is it?') ?></span>
        </a>
        <div class="dropdown-menu">
            <img src="<?php echo $this->getPubUrl('frontend/images/cvv.gif') ?>" alt="" />
        </div>
    </label>
    <input type="tel" id="authorizenet-verification" name="payment_data[verification]" class="form-control required cc-verification" autocomplete="off" disabled="disabled" data-msg-required="<?php echo $this->translate('Please enter verification number');?>(CVV)!" />
</div>