<?php
$current = $this->getUri()->withQuery('')->withFragment('')->__toString();
?>
<nav>    		
    <dl>
        <?php foreach ($this->getGroups() as $group): ?>
            <dt>
                <span class="fa fa-fw fa-<?php echo $group['icon'] ?>" aria-hidden="true"></span>
                <span><?php echo $this->translate($group['label']) ?></span>
            </dt>
            <?php foreach ($this->getLinks() as $link): ?>
                <?php if ($link['group'] == $group['label']): ?>
                    <dd<?php if (!empty($link['class'])): ?> class="<?php echo $link['class'] ?>"<?php endif ?>>
                        <a href="<?php echo $this->getBaseUrl($link['link']) ?>"<?php if (strpos($current, $link['link']) !== false): ?> class="active"<?php endif ?>>
                            <span><?php echo $this->translate($link['label']) ?></span>
                        </a>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>                
        <?php endforeach; ?>              
    </dl>
</nav>
